import TightVer401.PositiveExitConstructionSelectedSourceGeometryCore
import TightVer401.PositiveExitConstructionSelectedSourceGeometryPhase
import TightVer401.PositiveExitConstructionSelectedSourceGeometryFlowCore
import TightVer401.PositiveExitConstructionSelectedSourceGeometryOrientation
import TightVer401.PositiveExitConstructionSelectedSourceGeometryFlowDerivative
import TightVer401.PositiveExitConstructionSelectedSourceGeometryProjection
#print axioms TightVer401.positiveExit_selectedSourceGeometry_core_uniform_gap
#print axioms TightVer401.positiveExit_selectedSourceGeometry_exists_uniform_core_band
#print axioms TightVer401.positiveExit_selectedSourceGeometry_protected_agreement
#print axioms TightVer401.positiveExit_selectedSourceGeometry_core_in_flowCore
#print axioms TightVer401.positiveExit_selectedSourceGeometry_support_in_flowCore
#print axioms TightVer401.positiveExitFermiLabel_selected_exists_uniform_tube
#print axioms TightVer401.positiveExitSelected_exists_graph_amplitude_budget
#print axioms TightVer401.positiveExitSelected_graph_disjoint_of_label_tube
#print axioms TightVer401.positiveExitSelected_two_graphs_disjoint_of_label_tubes
#print axioms TightVer401.positiveExit_selectedSourceGeometry_central_gauss_cross
#print axioms TightVer401.positiveExit_selectedSourceGeometry_central_gauss_orientation

#print axioms TightVer401.positiveExit_selectedSourceGeometry_ruledFlow_initialValue_deriv_pos

#print axioms TightVer401.positiveExitSelected_gnomonic_annular_jacobian
#print axioms TightVer401.positiveExitSelected_gnomonic_annular_jacobian_neg

