import TightVer401.PositiveExitConstructionSelectedSourceGeometryAnnularJacobian
#print axioms TightVer401.positiveExitSelectedAnnularDescent_jacobian
#print axioms TightVer401.positiveExitSelectedAnnularDescent_jacobian_pos
