import TightVer401.PositiveExitConstructionSelectedSourceGeometrySelectedProtectedPair
import TightVer401.PositiveExitConstructionSelectedSourceGeometryProtectedWinding

namespace TightVer401
#print axioms positiveExitSelected_fermi_homotopy_avoids_protected
#print axioms positiveExitSelected_graph_to_seam_avoids_protected
#print axioms positiveExitSelected_seam_clock_avoids_protected
#print axioms positiveExit_protected_homotopy_integral_eq
#print axioms positiveExit_protected_homotopy_sides_iff
#print axioms positiveExit_protected_homotopy_inside
#print axioms positiveExit_protected_homotopy_exterior
#print axioms positiveExitSelected_graph_to_raw_avoids_protected
end TightVer401
