import TightVer401.PositiveExitConstructionSelectedSourceGeometryGaussBand
#print axioms TightVer401.positiveExit_selectedSourceGeometry_gauss_cross_pairing_det
#print axioms TightVer401.positiveExit_selectedSourceGeometry_ruled_tangent_cross
#print axioms TightVer401.positiveExit_selectedSourceGeometry_raw_gauss_signed_area_neg
#print axioms TightVer401.positiveExit_selectedSourceGeometry_raw_gnomonic_jacobian_neg
