import TightVer401.VisibleConnectorIncomingParametersActualDelta
import TightVer401.VisibleConnectorIncomingParametersCarrier
import TightVer401.VisibleConnectorIncomingParametersCoefficients
import TightVer401.VisibleConnectorIncomingParametersCompatible
import TightVer401.VisibleConnectorIncomingParametersDelta
import TightVer401.VisibleConnectorIncomingParametersEta
import TightVer401.VisibleConnectorIncomingParametersGinChoice
import TightVer401.VisibleConnectorIncomingParametersGinDelta
import TightVer401.VisibleConnectorIncomingParametersHeight
import TightVer401.VisibleConnectorIncomingParametersRho
import TightVer401.VisibleConnectorIncomingParametersSigns
import TightVer401.VisibleConnectorIncomingRebaseMatching
import TightVer401.VisibleConnectorIncomingRebaseOriginalTrace
import TightVer401.VisibleConnectorIncomingSeamEmbedding
import TightVer401.VisibleConnectorIncomingSeamJets
import TightVer401.VisibleConnectorIncomingTerminalActualStability
import TightVer401.VisibleConnectorIncomingTerminalLocalStability
import TightVer401.VisibleConnectorIncomingTerminalMargins
import TightVer401.VisibleConnectorIncomingTerminalPhase
import TightVer401.VisibleConnectorIncomingTerminalQuotient
import TightVer401.VisibleConnectorIncomingTerminalRebase
/-! Scoped axiom audit of every exported incoming producer declaration. -/

#print axioms TightVer401.visibleConnectorIncomingParameters_uniform_actual_lower_delta
#print axioms TightVer401.visibleConnectorIncomingParameters_uniform_source_domain
#print axioms TightVer401.visibleConnectorIncomingParameters_exists_rho_negative_strip
#print axioms TightVer401.visibleConnectorIncomingParametersFamilyPhaseDerivative
#print axioms TightVer401.visibleConnectorIncomingParametersFamilyA
#print axioms TightVer401.visibleConnectorIncomingParametersFamilyB
#print axioms TightVer401.visibleConnectorIncomingParametersFamilyC
#print axioms TightVer401.visibleConnectorIncomingParametersFamilyPhaseDerivative_actual
#print axioms TightVer401.visibleConnectorIncomingParametersFamilyPhaseDerivative_continuousOn
#print axioms TightVer401.visibleConnectorIncomingParametersFamily_coefficients_continuousOn
#print axioms TightVer401.visibleConnectorIncomingParametersFamily_coefficients_actual
#print axioms TightVer401.visibleConnectorIncomingParametersFamily_deriv_periodic
#print axioms TightVer401.visibleConnectorIncomingParametersFamily_actual_coefficients_continuousOn
#print axioms TightVer401.visibleConnectorIncomingParametersFamily_actual_coefficients_periodic
#print axioms TightVer401.visibleConnectorIncomingParameters_exists_compatible_rho
#print axioms TightVer401.visibleConnectorIncomingParameters_uniform_lower_delta
#print axioms TightVer401.visibleConnectorIncomingParameters_exists_eta_original_margins
#print axioms TightVer401.visibleConnectorIncomingParameters_exists_Gin_compatible_rho
#print axioms TightVer401.visibleConnectorIncomingParameters_uniform_Gin_lower_delta
#print axioms TightVer401.visibleConnectorIncomingParameters_uniform_height_small
#print axioms TightVer401.visibleConnectorIncomingParameters_exists_rho_below_margins
#print axioms TightVer401.visibleConnectorIncomingParameters_uniform_actual_coefficient_signs
#print axioms TightVer401.visibleConnectorIncomingRebase_cartesian_seam_matches
#print axioms TightVer401.visibleConnectorIncomingRebase_original_trace
#print axioms TightVer401.visibleConnectorIncomingSeam_displaced_isClosedEmbedding
#print axioms TightVer401.visibleConnectorIncomingSeam_trace_deriv
#print axioms TightVer401.visibleConnectorIncomingSeam_exists_local_matched_potential
#print axioms TightVer401.visibleConnectorIncomingTerminal_actualFamily_exists_positive_filling
#print axioms TightVer401.visibleConnectorIncomingTerminal_exists_local_periodic_displacement_threshold
#print axioms TightVer401.visibleConnectorIncomingTerminal_exists_local_displaced_positive_filling
#print axioms TightVer401.visibleConnectorIncomingTerminal_compact_norm_margin
#print axioms TightVer401.visibleConnectorIncomingTerminal_exists_escape_and_filling
#print axioms TightVer401.visibleConnectorIncomingTerminal_exists_enclosing_filling
#print axioms TightVer401.visibleConnectorIncomingTerminal_exists_displacement_threshold
#print axioms TightVer401.visibleConnectorIncomingTerminal_phase_surjective
#print axioms TightVer401.visibleConnectorIncomingTerminal_rebase_range_eq
#print axioms TightVer401.visibleConnectorIncomingTerminal_rebase_frontier
#print axioms TightVer401.visibleConnectorIncomingTerminal_familyPhaseDerivative_contDiffOn
#print axioms TightVer401.visibleConnectorIncomingTerminal_familyAC_contDiffOn
#print axioms TightVer401.visibleConnectorIncomingTerminalActualFamily
#print axioms TightVer401.visibleConnectorIncomingTerminal_actualFamily_contDiffOn
#print axioms TightVer401.visibleConnectorIncomingTerminal_actualFamily_C1
#print axioms TightVer401.visibleConnectorIncomingTerminal_rebase_eq
#print axioms TightVer401.visibleConnectorIncomingTerminal_rebase_deriv
#print axioms TightVer401.visibleConnectorIncomingTerminal_rebase_geometry
